Vagrant.configure("2") do |config|
        config.ssh.forward_x11 = true

	config.vm.define "server" do |server|
		server.vm.network "private_network", ip: "192.168.254.200"
		server.vm.hostname = "server"
                server.vm.box      = "centos/7"
	end

	config.vm.define "wordpress" do |wordpress|
		wordpress.vm.network "private_network", ip: "192.168.254.201"
		wordpress.vm.hostname = "wordpress"
                wordpress.vm.box      = "centos/7"
	end
       
        config.vm.define "banco" do |banco|
                banco.vm.network "private_network", ip: "192.168.254.202"
                banco.vm.hostname = "banco"
                banco.vm.box      = "debian/jessie64"
        end        
end
