Vagrant.configure("2") do |config|
        config.ssh.forward_x11 = true

# Configurando Maquinas Virtuais
	config.vm.define "dockersrv" do |dockersrv|
		dockersrv.vm.network "private_network", ip: "192.168.254.200"
		dockersrv.vm.hostname = "DockerSrv"
                dockersrv.vm.box      = "ubuntu/xenial64"
		dockersrv.vm.provider "virtualbox" do |v|
		   v.memory = 4096
		end
		dockersrv.vm.provision "shell", inline: <<-SHELL
		 curl -sSL https://get.docker.com/ | sh
                 usermod -aG docker vagrant
		 systemctl enable docker
		 init 6
		SHELL
        end 
end
