Vagrant.configure("2") do |config|
        config.ssh.forward_x11 = true
        config.vm.box          = "ubuntu/xenial64"

#Configurando Maquinas
	config.vm.define "pc1" do |pc1|
		pc1.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: true
		pc1.vm.hostname = "Computador1"
	end

        config.vm.define "pc2" do |pc2|
                pc2.vm.network "private_network", ip: "192.168.1.20", virtualbox__intnet: true
                pc2.vm.hostname = "Computador2"
        end        
end
